---
title: "mosquito"
output: html_document
---
```{r}

#install.packages("pracma")
#install.packages("matlib")
#install.packages("NlcOptim")
library("pracma")
library("matlib")


#sample data
#mosquito count from data
y_in = c(15, 40, 45, 88, 99, 145, 111, 132, 177, 97, 94, 145, 123, 111,
    125, 115, 155, 160, 143, 132, 126, 125, 105, 98, 87, 54, 55, 8)

#day of year in which measurments making up yin occur, Jan 1st = day 1
t_in_user = c(93, 100, 107, 114, 121, 128, 135, 142, 149, 163, 170, 177,
    184, 191, 198, 205, 212, 219, 226, 233, 240, 247, 254, 261,
    267, 274, 281, 288)


#if (length(y_in) != length(t_in_user)){
#  stop("input data mismatch")
#}
    
```

```{r}
#y_in = numeric(150)
#t_in_user = numeric(150)

#for (i in 1 : 150) {
#  y_in[i] = runif(1, 0.0, 150.0)
#  t_in_user[i] = 54 + i
#}

```


```{r}
# User inputs (aside from trap data inputs)

#mu = natural mosquito death rate 
mu = 1/14 #program should set mu = 1 / tau_mosq, where tau_mosq is the mosquito lifetime input by user in units of days 
          # tau_mosq should be bounded between 1 and 30 

#m = number of mosquito lifetimes for population decay between seasons..
m = 3 #this will be input by the user, and must be an integer greater than 2, upperbound 100, default value 3

# N_lam = max fourier mode order to calculate
N_lam = 45; #user input between 1 and 100, default value 25 (I referred to this as jmax over Skype - JD)

```


```{r}
#setting up time and trap count vectors to fit the model to 


#first round user time inputs to integer values
t_in = round(t_in_user)


#defining N0 = number of input data points (not a user input)
N0 = length(y_in)

#defining vector of time differences to be used later (not a user input)
delta_t_in = numeric(N0-1) 
for (i in 1:(N0-1)){
  delta_t_in[i] = t_in[i+1]-t_in[i]
  if (delta_t_in[i] < 0)
      stop("non-increasing measurement times")
}



#N_pts = number of points in extended data set, N_pts = N0 + 3 always (not a user input)
N_pts = N0 + 3

#defining extended trap count and time data vectors
t_dat = numeric(N_pts)

if (t_in[1] - m / mu > 0){
 y_dat = c(0,0, y_in,0)
 
 t_dat[1] = 0
 t_dat[2] = (m -1) / mu
 for (i in 3 : (N_pts - 1)){
  t_dat[i] = t_in[i - 2] - t_in[1] + m / mu
 }
 t_dat[N_pts] = t_dat[N_pts - 1] + (m) / mu

 t_dat=matrix(t_dat, ncol=1)
 
} else {
  y_dat = c(0, y_in, 0,0)
  
  t_dat[1] = 0
  for (i in 2: (N_pts - 2)){
    t_dat[i] = t_in[i - 1]
  }
  t_dat[N_pts - 1] = t_dat[N_pts - 2] + (2*(m - 1)) / mu - t_dat[2]
  t_dat[N_pts] = t_dat[N_pts - 1] + 1 / mu
}
  

#extended vector of time differences
delta_t_dat = numeric(N_pts)
for (i in 1 : (N_pts - 1)){
  delta_t_dat[i] = t_dat[i + 1] - t_dat[i]
}
    
delta_t_dat[N_pts] = 0

delta_t_dat= matrix(delta_t_dat,ncol=1)

#tau = length of 'season' in days
tau = t_dat[N_pts];

```


```{r}
#Defining matrices 'J' and 'M'
                  
#J matrix and inverse
J = matrix(0, nrow= N_pts, ncol=N_pts)

for (i in 1 : (N_pts - 1)){
  J[i, i] = 1
  J[i + 1, i] = -exp(-mu*delta_t_dat[i])
}

J[N_pts, N_pts] = 1;
J[1, N_pts] = -exp(-mu * delta_t_dat[N_pts])


#M matrix and inverse
M = matrix(0, nrow= N_pts, ncol=N_pts)

for (i in 2 : (N_pts - 1)){
  M[i, i] = (1 - exp( -mu * delta_t_dat[i - 1] ) ) /(mu * delta_t_dat[i - 1] ) - exp( -mu * delta_t_dat[i - 1])
  M[i + 1, i] =1- ( 1 - exp(-mu * delta_t_dat[i]) )/(mu * delta_t_dat[i])
}

M[N_pts, N_pts] = (1 - exp( (-1)*mu * delta_t_dat[N_pts - 1] ) ) /(mu * delta_t_dat[(N_pts - 1)] ) -exp( -mu * delta_t_dat[(N_pts - 1)])
M[1, N_pts] = 0
M[1, 1] = 0
M[2, 1] = 1- ( 1 - exp(-mu * delta_t_dat[1]) )/(mu * delta_t_dat[(1)]) 



###### new code
#Weight matrix: diagonal entries to be filled with sqrt(number of counts on day) except for the artifical 0 measurments on end of data
W = matrix(0, nrow= N_pts, ncol=N_pts)

if( t_in[(1)] - m / mu > 0){
  
  W[1,1] = 1
  W[2,2] = 1
  W[N_pts,N_pts] = 1 
      
  for(i in 3 : N_pts-1){
    W[i,i] = sqrt(50) #fill sqrt(number of counts here)
  }
} else {
  
  W[1,1] = 1
  W[N_pts-1,N_pts-1] = 1
  W[N_pts,N_pts] = 1 
      
  for(i in 2 : N_pts-2){
    W[i,i] = sqrt(50) #fill sqrt(number of counts here)
  }
}



```


```{r}

#Obtaining emergence rate vector lambda_dat by contrained optimization

Aeq = matrix(numeric(N_pts), nrow=1)
Aeq[(1)] = 1
Aeq[(N_pts)] = -1
beq = 0
bineq = numeric(N_pts)
lb = numeric(N_pts)
###################  



objective_fun = function(x) {t( W %*% ( (1 / mu) * (mldivide(J, (M %*% x), pinv = TRUE)) - y_dat) )%*%( W %*% ((1 / mu) * (mldivide(J, (M %*% x), pinv = TRUE)) - y_dat))}


lambda_dat = fmincon(numeric(N_pts), objective_fun, gr= NULL, method="SQP", A= (-(1 / mu) *( inv(J) %*%  (M))), b=bineq, Aeq = Aeq, beq = beq, lb = lb, ub = NULL)

#########

```



```{r}
 #Calculating emergence rate fourier modes lam_fourier

lam_fourier = numeric(N_lam + 1);



for (j in 1 : (N_pts-1)){
  lam_fourier[1] =  lam_fourier[1] + (1 / tau)*( lambda_dat$par[j] + lambda_dat$par[j + 1] ) * delta_t_dat[j] / 2
} #zero mode
    

for (k in 2 : (N_lam + 1)) #non-zero postive modes (negative modes given by complex conjugates of positve modes) 
{
  for (j in 1 : (N_pts - 1)){
    lam_fourier[(k)] = lam_fourier[(k)] +( ( lambda_dat$par[(j + 1)] - lambda_dat$par[(j)] )  / delta_t_dat[(j)] ) *( tau / (2 * pi * (k-1) ) )* ( ( exp(- 2 * pi * complex(real = 0, imaginary = 1) * (k-1) * t_dat[(j + 1)] / tau ) -exp(- 2 * pi * complex(real = 0, imaginary = 1) * (k-1) * t_dat[(j)]/ tau) ) / (2 * pi * (k-1)) )+ complex(real = 0, imaginary = 1) * ( lambda_dat$par[(j + 1)] * exp(- 2 * pi * complex(real = 0, imaginary = 1) * (k-1) * t_dat[(j + 1)] / tau ) -lambda_dat$par[(j)] * exp(- 2 * pi * complex(real = 0, imaginary = 1) * (k-1) * t_dat[(j)] /tau ) ) / (2 * pi * (k-1) )
  }
}
```

```{r}
#Obtaining fitted curves

t_steps = 6 * tau*10 + 1

t_vec = linspace(0, 6*tau, n = t_steps);
lambda_fourier_function = numeric(t_steps)
y_fourier_uncontrolled = numeric(t_steps)
val_fourier = numeric(t_steps)





for( i in 1:t_steps){
    lambda_fourier_function[i] = lam_fourier[1]
    for( j in 2 : (N_lam + 1)){
        lambda_fourier_function[i] = lambda_fourier_function[i] + lam_fourier[(j)] * 
          exp( 2 * pi * complex(real = 0, imaginary = 1) * (j-1) * t_vec[(i)]/ tau) +
            Conj(lam_fourier[(j)]) * exp( -2 * pi * complex(real = 0, imaginary = 1) * (j-1) * t_vec[(i)] / tau)
    }
    
}

for( i in 1:t_steps){
    
    for( j in 2: (N_lam + 1)){
        val_fourier[(i)] = val_fourier[(i)] + lam_fourier[(j)] * 
          ( tau / (2 * pi * complex(real = 0, imaginary = 1) *(j-1) + mu * tau) )*
            ( exp( 2* pi * complex(real = 0, imaginary = 1) * (j-1) * t_vec[(i)] / tau) - 
                exp(-mu * t_vec[(i)] )) + 
          Conj(lam_fourier[(j)]) * ( tau / (-2 * pi * complex(real = 0, imaginary = 1) *(j-1) + mu * tau ) )*
            ( exp( -2* pi * complex(real = 0, imaginary = 1) * (j-1)* t_vec[(i)] / tau) - exp(-mu * t_vec[(i)] ))
    }
}



for(k in 2:t_steps){    
    
    
   y_fourier_uncontrolled[k] = y_dat[1] * exp(- mu * t_vec[k]) +
       (lam_fourier[1] / mu ) * (1 - exp(-mu * t_vec[k])) +  val_fourier[k]
    
}


y_uncontrolled_plot = numeric(10 * tau + 1)
lambda_fourier_plot = numeric(10 * tau + 1)
t_vec_plot = numeric(10 * tau + 1)


for( i in 1 : (10*tau+1)){

    
    y_uncontrolled_plot[i] = y_fourier_uncontrolled[(i + 10*tau*5)];
    lambda_fourier_plot[(i)] = lambda_fourier_function[(i+ 10*tau*5)];
    
    # old code t_vec_plot[(i)] = t_vec[(i)];
    
    #new code shifts times back to orginal values for model output
    if( t_in[1] - m / mu > 0){
        t_vec_plot[(i)] = t_vec[(i)]-t_dat[(3)] +t_in[(1)];
    } else {
        t_vec_plot[(i)] = t_vec[(i)] -t_dat[(2)] + t_in[(1)];

    }
}


#new code shifts times back to orginal values for data point plotting
t_dat_plot = numeric(N_pts)
for(i in 1:N_pts){
  
  if( t_in[(1)] - m / mu > 0){
      t_dat_plot[i] = t_dat[i]  - t_dat[(3)] + t_in[(1)];
  } else {
      t_dat_plot[i] = t_dat[i]  - t_dat[(2)] + t_in[(1)];
  }
}
#also change what was previously t_dat to t_dat_plot for the plotting code in the next two chunks

```



```{r}
#plotting fitted curves



plot(t_dat_plot, y_dat, ylim = c(0,1.5 * max(y_dat)), xlim=c(t_dat_plot[1],t_dat_plot[1]+tau), col="blue",
     main="Fitted Population Model",
ylab="Mosquito population count",
xlab="Day of year")
lines(t_vec_plot,y_uncontrolled_plot, col="red")
legend("topleft",c("Data","Fitted Fourier Approximation"),fill=c("blue","red"))



    
```
```{r}


plot(t_dat_plot, lambda_dat$par, ylim = c(0,1.5 * max(lambda_dat$par)), xlim=c(t_dat_plot[1],t_dat_plot[1]+tau), col="blue",
main="Fitted Emergence Rate Function",
ylab="Emergence rate",
xlab="Day of year")
lines(t_vec_plot,lambda_fourier_plot, col="red")
legend("topleft",c("Fitted Values","Fourier Approximation"),fill=c("blue","red"))


```
